# Generated by Django 5.2.6 on 2026-04-24 07:20

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text='Used in topics: iot/v1/{slug}/…', max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('device_id', models.UUIDField(db_index=True, default=uuid.uuid4, help_text='Must match the device_id segment in MQTT and in the JSON envelope.', unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('topic_prefix', models.CharField(blank=True, help_text='Optional override; leave empty to use iot/v1/{org_slug}/{device_id}/…', max_length=500)),
                ('last_seen_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('last_channel', models.CharField(blank=True, editable=False, max_length=100)),
                ('last_schema', models.CharField(blank=True, editable=False, max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='iot.organization')),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
                'ordering': ('organization', 'name'),
                'indexes': [models.Index(fields=['organization', 'device_id'], name='iot_device_organiz_6f9405_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrganizationMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('member', 'Member'), ('viewer', 'Viewer')], default='member', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='iot.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iot_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Organization membership',
                'verbose_name_plural': 'Organization memberships',
                'ordering': ('organization__name', 'user__email'),
                'constraints': [models.UniqueConstraint(fields=('user', 'organization'), name='iot_membership_user_org_uniq')],
            },
        ),
    ]
