# Generated by Django 5.2.6 on 2026-04-24 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(help_text='Nama unik; tidak boleh sama dengan organisasi lain (abaikan huruf besar/kecil).', max_length=255),
        ),
        migrations.AlterField(
            model_name='organization',
            name='slug',
            field=models.SlugField(blank=True, help_text='Dibuat otomatis dari nama. Dipakai di topik MQTT: iot/v1/{slug}/…', max_length=255, unique=True),
        ),
    ]
