# Generated by Django 5.2.6 on 2026-04-24 09:07

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0002_organization_slug_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='reported_firmware_version',
            field=models.CharField(blank=True, help_text='Set after successful OTA (device report).', max_length=100),
        ),
        migrations.CreateModel(
            name='FirmwarePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(default='default', help_text='Group builds (e.g. hardware SKU).', max_length=100)),
                ('version', models.CharField(help_text='Version label shown to the device and stored after success (e.g. 1.4.0).', max_length=64)),
                ('file', models.FileField(upload_to='iot/firmware/%Y/%m/')),
                ('sha256', models.CharField(blank=True, editable=False, max_length=64)),
                ('file_size', models.PositiveIntegerField(default=0, editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name': 'Firmware package',
                'verbose_name_plural': 'Firmware packages',
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(fields=('product', 'version'), name='iot_firmware_product_version_uniq')],
            },
        ),
        migrations.CreateModel(
            name='DeviceOTAJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Command sent (MQTT)'), ('in_progress', 'In progress (device)'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('command_sent_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('completed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ota_jobs', to='iot.device')),
                ('firmware', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ota_jobs', to='iot.firmwarepackage')),
            ],
            options={
                'verbose_name': 'Device OTA job',
                'verbose_name_plural': 'Device OTA jobs',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status', 'created_at'], name='iot_deviceo_status_20b659_idx')],
            },
        ),
    ]
