# Generated by Django 5.2.6 on 2026-04-29 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0003_ota_and_reported_firmware'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='firmware_product',
            field=models.CharField(default='default', help_text='Must match FirmwarePackage.product for OTA (e.g. hardware SKU).', max_length=100),
        ),
    ]
