# Generated by Django 5.2.6 on 2026-05-05 04:02

import apps.IoT.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0004_device_firmware_product_ota_flow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='hardware_version',
            field=models.CharField(blank=True, help_text="Hardware revision (e.g., 'rev2', 'v1.1') for firmware compatibility checks.", max_length=32),
        ),
        migrations.CreateModel(
            name='FirmwareVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(db_index=True, default='default', help_text="Product SKU or hardware type (e.g., 'solar-controller-v2').", max_length=100)),
                ('version', models.CharField(db_index=True, help_text='Semantic version (e.g., 1.4.0, 2.0.0-beta.1).', max_length=64)),
                ('file', models.FileField(help_text='Firmware binary file (.bin, .elf, .hex). Stored in isolated folder per version.', upload_to=apps.IoT.models.firmware_upload_path)),
                ('sha256', models.CharField(blank=True, editable=False, help_text='SHA256 hash of the file for integrity verification.', max_length=64)),
                ('file_size', models.PositiveIntegerField(default=0, editable=False, help_text='File size in bytes.')),
                ('is_active', models.BooleanField(default=True, help_text='Only active versions can be deployed via OTA.')),
                ('is_mandatory', models.BooleanField(default=False, help_text='Mark as mandatory update - devices will be forced to update.')),
                ('release_notes', models.TextField(blank=True, help_text='Release notes describing changes in this version.')),
                ('min_hardware_version', models.CharField(blank=True, help_text="Minimum hardware version required (e.g., 'rev2'). Leave empty for all.", max_length=32)),
                ('max_hardware_version', models.CharField(blank=True, help_text="Maximum hardware version supported (e.g., 'rev4'). Leave empty for all.", max_length=32)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_firmware_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Firmware Version',
                'verbose_name_plural': 'Firmware Versions',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AlterField(
            model_name='deviceotajob',
            name='firmware',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ota_jobs', to='iot.firmwareversion'),
        ),
        migrations.AddConstraint(
            model_name='firmwareversion',
            constraint=models.UniqueConstraint(fields=('product', 'version'), name='iot_firmware_version_product_version_uniq'),
        ),
        migrations.DeleteModel(
            name='FirmwarePackage',
        ),
    ]
