# Generated by Django 5.2.6 on 2026-07-22 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0008_organization_stable_identity'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='devicecommand',
            new_name='iot_devicec_device__c73f4e_idx',
            old_name='iot_devicec_device__066551_idx',
        ),
        migrations.RenameIndex(
            model_name='deviceevent',
            new_name='iot_devicee_organiz_9d99ad_idx',
            old_name='iot_devicee_organiz_31e3f9_idx',
        ),
        migrations.RenameIndex(
            model_name='mqttoutboxmessage',
            new_name='iot_mqttout_status_8872e3_idx',
            old_name='iot_mqttout_status_f0ce99_idx',
        ),
        migrations.RenameIndex(
            model_name='telemetryrecord',
            new_name='iot_telemet_device__043fce_idx',
            old_name='iot_teleme_device__c906fd_idx',
        ),
        migrations.RenameIndex(
            model_name='telemetryrecord',
            new_name='iot_telemet_schema_ca6bde_idx',
            old_name='iot_teleme_schema_2c4ddf_idx',
        ),
    ]
